#!/usr/bin/env python2
import sys

minX = 1600
minY =    0
maxX = 4000
maxY = 2500

with open(sys.argv[1]) as f:
    first = True
    for line in f.readlines():
        if first:
            first = False
            continue
        x0,y0, x1,y1, s,f = line.split(' ')
        x0 = int(x0);
        x1 = int(x1);
        y0 = int(y0);
        y1 = int(y1);

        if x0 < minX or maxX < x0:
            continue
        if x1 < minX or maxX < x1:
            continue

        if y0 < minY or maxY < y0:
            continue
        if y1 < minY or maxY < y1:
            continue

        sys.stdout.write(line)
