#!/usr/bin/env python2
import sys

minX = 1600
minY =    0
maxX = 4000
maxY = 2500

with open(sys.argv[1]) as f:
    first = True
    for line in f.readlines():
        if first:
            first = False
            continue
        x0,y0, x1,y1, s,f = line.split(' ')

        longLine = s + " "

        x0 = int(x0);
        x1 = int(x1);
        y0 = int(y0);
        y1 = int(y1);

        dist = abs(x1-x0) + abs(y1-y0)
        time = abs(int(s)-int(f))

        longLine += str(dist) + " " + str(time) + "\n"


        if x0 < minX or maxX < x0:
            sys.stdout.write(longLine)
            continue
        if x1 < minX or maxX < x1:
            sys.stdout.write(longLine)
            continue

        if y0 < minY or maxY < y0:
            sys.stdout.write(longLine)
            continue
        if y1 < minY or maxY < y1:
            sys.stdout.write(longLine)
            continue
